// Seed/demo fixtures for local development and the demo build only.
// MUST NOT be imported by production code paths. Imports must be either
// gated behind `import.meta.env.DEV` or performed via dynamic import inside
// a dev-only branch so Vite tree-shakes them out of the production bundle.

import type { Performer, Booking, DoNotServeEntry, Communication } from '../../../types';

export const mockPerformers: Performer[] = [
  {
    id: 5,
    name: 'April',
    tagline: 'Sweet, sassy, and always a delight.',
    photo_url: 'https://picsum.photos/seed/april/800/1200',
    bio: 'April brings a fresh and exciting energy to every event. With a background in dance and modeling, she captivates audiences and ensures a memorable experience. She is perfect for high-energy parties and promotional events.',
    service_ids: ['waitress-topless', 'show-hot-cream', 'show-pearl', 'show-deluxe-works', 'misc-promo-model'],
    service_areas: ['Perth North', 'Perth South'],
    status: 'available',
    rating: 4.9,
    review_count: 124,
    min_booking_duration_hours: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 1,
    name: 'Scarlett',
    tagline: 'The life of the party, guaranteed.',
    photo_url: 'https://picsum.photos/seed/scarlett/800/1200',
    bio: 'With over a decade of experience in corporate events and private parties, Scarlett knows exactly how to get the crowd going. Her vibrant personality and professional demeanor make her a favorite for any occasion.',
    service_ids: ['waitress-topless', 'waitress-nude', 'show-hot-cream', 'misc-atmospheric'],
    service_areas: ['Perth North', 'Perth South', 'Southwest'],
    status: 'available',
    rating: 4.8,
    review_count: 215,
    min_booking_duration_hours: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Jasmine',
    tagline: 'Elegance and charm for your special event.',
    photo_url: 'https://picsum.photos/seed/jasmine/800/1200',
    bio: 'Jasmine specializes in high-end events, bringing a touch of class and sophistication. Her background in theatre and performing arts ensures a captivating experience for all guests.',
    service_ids: ['misc-promo-model', 'misc-atmospheric', 'waitress-lingerie'],
    service_areas: ['Perth South'],
    status: 'busy',
    rating: 4.7,
    review_count: 56,
    min_booking_duration_hours: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Amber',
    tagline: 'Bringing warmth and energy to every room.',
    photo_url: 'https://picsum.photos/seed/amber/800/1200',
    bio: 'Amber’s infectious energy and friendly approach make her perfect for creating a relaxed and fun atmosphere. She excels at making guests feel comfortable and ensuring everyone has a memorable time.',
    service_ids: ['waitress-topless', 'misc-games-host', 'show-pearl'],
    service_areas: ['Perth North', 'Northwest'],
    status: 'available',
    rating: 4.9,
    review_count: 142,
    min_booking_duration_hours: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Chloe',
    tagline: 'Professional, punctual, and always polished.',
    photo_url: 'https://picsum.photos/seed/chloe/800/1200',
    bio: 'Chloe prides herself on her professionalism and attention to detail. She seamlessly integrates into any event, providing top-tier service and ensuring everything runs smoothly from start to finish.',
    service_ids: ['misc-promo-model', 'misc-atmospheric', 'waitress-lingerie'],
    service_areas: ['Southwest'],
    status: 'offline',
    rating: 4.6,
    review_count: 38,
    min_booking_duration_hours: 2,
    created_at: new Date().toISOString(),
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'demo-booking-1',
    performer_id: 1,
    client_name: 'Demo Client A',
    client_email: 'demo-a@example.test',
    client_phone: '0400000001',
    event_date: '2024-08-15',
    event_time: '19:00',
    event_address: '123 Demo Street, Perth WA',
    event_type: 'Corporate Gala',
    status: 'confirmed',
    payment_status: 'fully_paid',
    id_document_path: null,
    selfie_document_path: null,
    deposit_receipt_path: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    duration_hours: 4,
    number_of_guests: 50,
    services_requested: ['waitress-topless'],
    verified_by_admin_name: 'Demo Admin',
    verified_at: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    client_message: 'Demo confirmed booking.',
    performer: { id: 1, name: 'Scarlett' },
    performer_eta_minutes: 25,
  },
  {
    id: 'demo-booking-2',
    performer_id: 2,
    client_name: 'Demo Client B',
    client_email: 'demo-b@example.test',
    client_phone: '0400000002',
    event_date: '2024-08-22',
    event_time: '20:30',
    event_address: '456 Demo Ave, Fremantle WA',
    event_type: 'Birthday Celebration',
    status: 'pending_deposit_confirmation',
    payment_status: 'deposit_paid',
    id_document_path: 'demo/id.pdf',
    selfie_document_path: 'demo/selfie.jpg',
    deposit_receipt_path: 'demo/receipt.jpg',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    duration_hours: 3,
    number_of_guests: 20,
    services_requested: ['waitress-lingerie'],
    verified_by_admin_name: null,
    verified_at: null,
    client_message: null,
    performer: { id: 2, name: 'Jasmine' },
    performer_eta_minutes: 30,
  },
];

export const mockDoNotServeList: DoNotServeEntry[] = [
  {
    id: 'demo-dns-1',
    client_name: 'Demo Blocked User',
    client_email: 'demo-blocked@example.test',
    client_phone: '0400999000',
    reason: 'Demo entry illustrating an approved DNS record.',
    status: 'approved',
    submitted_by_performer_id: 1,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    performer: { name: 'Scarlett' },
  },
  {
    id: 'demo-dns-2',
    client_name: 'Demo Pending Report',
    client_email: 'demo-pending@example.test',
    client_phone: '0400999001',
    reason: 'Demo entry illustrating a pending DNS submission.',
    status: 'pending',
    submitted_by_performer_id: 2,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    performer: { name: 'Jasmine' },
  },
];

export const mockCommunications: Communication[] = [
  {
    id: 'demo-comm-1',
    sender: 'System',
    recipient: 'admin',
    message: 'Demo booking demo-booking-1 was confirmed.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    booking_id: 'demo-booking-1',
  },
  {
    id: 'demo-comm-2',
    sender: 'System',
    recipient: 1,
    message: 'Your demo booking is confirmed.',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    booking_id: 'demo-booking-1',
  },
];
